sex 20 set 2024 21:43:30 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -121,7 +121,8 @@ runs:
           tree \
           duf \
           chili-nanorc \
-          chili-bashrc > /dev/null
+          chili-bashrc \
+          inetutils > /dev/null
 
     - name: Ajustar ambiente do builduser
       shell: bash
@@ -152,8 +153,11 @@ runs:
     - name: Configurar o ambiente para o usuário root e builduser
       shell: bash
       run: |
-        WORK_PATH='/__w/build-iso/build-iso'
-        PROFILE_PATH='/__w/build-iso/build-iso/iso-profiles/community'
+        #WORK_PATH='/__w/build-iso/build-iso'
+        #PROFILE_PATH='/__w/build-iso/build-iso/iso-profiles/community'
+        WORK_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}"
+        PROFILE_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}/iso-profiles/community"
+
         echo "WORK_PATH=$WORK_PATH" >> $GITHUB_ENV  # Exporta WORK_PATH para outras etapas
         echo "PROFILE_PATH=$PROFILE_PATH" >> $GITHUB_ENV  # Exporta WORK_PATH para outras etapas
 
@@ -218,6 +222,7 @@ runs:
         PATH_MANJARO_ISO_PROFILES: "/usr/share/manjaro-tools/iso-profiles"
         PATH_MANJARO_TOOLS: "/usr/share/manjaro-tools"
         VAR_CACHE_MANJARO_TOOLS: "/var/cache/manjaro-tools"
+        VAR_CACHE_MANJARO_TOOLS_ISO: "/var/cache/manjaro-tools/iso"
       run: |
         # Configuring repositories and build environment
         # Função para adicionar repositórios
@@ -420,6 +425,7 @@ runs:
         PATH_MANJARO_ISO_PROFILES: "/usr/share/manjaro-tools/iso-profiles"
         PATH_MANJARO_TOOLS: "/usr/share/manjaro-tools"
         VAR_CACHE_MANJARO_TOOLS: "/var/cache/manjaro-tools"
+        VAR_CACHE_MANJARO_TOOLS_ISO: "/var/cache/manjaro-tools/iso"
       run: |
         # BUILD ISO Image
 
@@ -437,55 +443,6 @@ runs:
 
         # listando diretório iso-profiles no diretório atual
         ls -la "$PROFILE_PATH"
-
-        setup_manjaro_tools() {
-          # Criar e configurar diretórios
-          mkdir -p "$VAR_CACHE_MANJARO_TOOLS/iso"
-          chmod 777 "$VAR_CACHE_MANJARO_TOOLS/iso"
-
-          # Verificar se buildiso está disponível
-          if ! command -v buildiso &> /dev/null; then
-            echo "Error: buildiso command not found. Please ensure manjaro-tools-iso is installed correctly."
-            exit 1
-          fi
-
-          # Verificar se o diretório do perfil existe
-          if [[ ! -d "$PROFILE_PATH/$EDITION" ]]; then
-            echo "Error: Profile directory $PROFILE_PATH/$EDITION does not exist."
-            exit 1
-          fi
-
-          # Configurar o nome da distribuição e ISO
-          sed -i 's|dist_name=\$(get_distname)|dist_name=BigCommunity|g' /usr/lib/manjaro-tools/util.sh
-          sed -i 's|iso_name=\$(get_osid)|iso_name=bigcommunity|g' /usr/lib/manjaro-tools/util.sh
-
-          # Configurar a marca do BigCommunity
-          sed -i -e 's|dist_branding=.*|dist_branding="bigcommunity"|' /usr/lib/manjaro-tools/util.sh
-
-          # Modificar o nome do arquivo ISO
-          sed -i 's|_${profile}${_edition}_${dist_release//.}|-live|' /usr/lib/manjaro-tools/util-iso.sh
-
-          # Modificar a busca por versões de kernel
-          sed -i '/_kernver=/s/_kernver=.*/_kernver=$(find $1\/usr\/lib\/modules\/ -type f -name version -exec cat {} +)/' /usr/lib/manjaro-tools/util-iso-boot.sh
-
-          # Desabilitar a verificação de versão do kernel
-          sed -i '/${iso_kernel}/s/^/#/' /usr/lib/manjaro-tools/util-iso.sh
-
-          # Configurar o caminho do perfil ISO
-          sed -i "s|^iso_profile=.*|iso_profile=\"$PROFILE_PATH\"|" /etc/manjaro-tools/manjaro-tools.conf
-
-          # Adicionar limpezas do Big
-          add_big_cleanups
-
-          # Adicionar root-overlay
-          sed -i '/copy_overlay "${profile_dir}\/root-overlay" "${path}"/a [[ -e ${profile_dir}\/root-overlay ]] && copy_overlay "${profile_dir}\/root-overlay" "${path}"' /usr/lib/manjaro-tools/util-iso.sh
-
-          # Habilitar plymouth e kms
-          sed -i "s|keyboard keymap|keyboard keymap kms plymouth|g" "$PATH_MANJARO_TOOLS/mkinitcpio.conf"
-
-          echo "Manjaro tools setup completed. Directory contents of /var/cache/manjaro-tools/iso:"
-          ls -la "$VAR_CACHE_MANJARO_TOOLS/iso"
-        }
 
         add_big_cleanups() {
           # cleanups
@@ -521,8 +478,8 @@ runs:
             echo "Setting up Manjaro tools..."
 
             # Criar e configurar diretórios
-            mkdir -p /var/cache/manjaro-tools/iso
-            chmod 777 /var/cache/manjaro-tools/iso
+            mkdir -p "$VAR_CACHE_MANJARO_TOOLS_ISO"
+            chmod 1777 "$VAR_CACHE_MANJARO_TOOLS_ISO"
 
             # Verificar se buildiso está disponível
             if ! command -v buildiso &> /dev/null; then
@@ -561,8 +518,8 @@ runs:
             # Habilitar plymouth e kms
             sed -i "s|keyboard keymap|keyboard keymap kms plymouth|g" /usr/share/manjaro-tools/mkinitcpio.conf
 
-            echo "Manjaro tools setup completed. Directory contents of /var/cache/manjaro-tools/iso:"
-            ls -la /var/cache/manjaro-tools/iso
+            echo "Manjaro tools setup completed. Directory contents of $VAR_CACHE_MANJARO_TOOLS_ISO:"
+            ls -la "$VAR_CACHE_MANJARO_TOOLS_ISO"
         }
 
         configure_mesa() {
@@ -772,7 +729,7 @@ runs:
           echo "###################################################################"
 
           # Executar buildiso e capturar o código de saída
-          if [[ $DEBUG == 'true' ]]; then
+          if [[ "$DEBUG" == 'true' ]]; then
             #sudo buildiso "${SCOPE:+-f}" -p "community/$EDITION" -b "$MANJAROBRANCH" -k "linux${KERNEL_NAME}" "${OFFICE:+-o}"
             su -c "buildiso ${SCOPE:+-f} -p community/$EDITION -b $MANJAROBRANCH -k linux${KERNEL_NAME} ${OFFICE:+-o}; exit \$?" builduser
           else
@@ -782,16 +739,16 @@ runs:
           BUILD_EXIT_CODE=$?
 
           # Verificar arquivos de kernel e tentar cópia manual, independentemente do resultado do buildiso
-          echo "Checking kernel files in rootfs:"
+          # Checking kernel files in rootfs:"
           find /var/lib/manjaro-tools/buildiso/${EDITION}/x86_64/rootfs/boot -name "vmlinuz*"
 
-          echo "Checking kernel files in iso/boot:"
+          # Checking kernel files in iso/boot:"
           find /var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot -name "vmlinuz*"
 
           if [ ! -f "/var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot/vmlinuz*" ]; then
-            echo "Warning: Kernel file not found in iso/boot. Attempting manual copy..."
+            # Warning: Kernel file not found in iso/boot. Attempting manual copy
             mkdir -p "/var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot"
-            cp /var/lib/manjaro-tools/buildiso/${EDITION}/x86_64/rootfs/boot/vmlinuz* "/var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot/" || echo "Manual copy failed"
+            cp -v /var/lib/manjaro-tools/buildiso/${EDITION}/x86_64/rootfs/boot/vmlinuz* "/var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot/" || echo "Manual copy failed"
           fi
 
           # Exibir conteúdo de diretórios relevantes para diagnóstico
@@ -809,8 +766,10 @@ runs:
         }
 
         cleanup_and_move_files() {
-          OUTPUT_ISO_PATH_NAME=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
-          FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+          #OUTPUT_ISO_PATH_NAME=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+          #FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+          OUTPUT_ISO_PATH_NAME=$(find "$VAR_CACHE_MANJARO_TOOLS_ISO" -type f -name "*.iso" -printf '%T@ %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)
+          FILE_PKG=$(find "$VAR_CACHE_MANJARO_TOOLS_ISO" -type f -name "*-pkgs.txt" -printf '%T@ %p\n' | sort -nr | head -n 1 | cut -d' ' -f2-)
 
           echo "ISO_BASENAME=$ISO_BASENAME"                 >> "$GITHUB_ENV"  # Exporta ISO_BASENAME para outras etapas
           echo "OUTPUT_ISO_PATH_NAME=$OUTPUT_ISO_PATH_NAME" >> "$GITHUB_ENV"  # Exporta OUTPUT_ISO_PATH_NAME para outras etapas
