ter 24 set 2024 06:06:14 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/mkiso-bigcommunity b/mkiso-bigcommunity
--- a/mkiso-bigcommunity
+++ b/mkiso-bigcommunity
@@ -527,7 +527,7 @@ export -f configure_iso_name
 
 build_iso() {
 	echo "########################## RESUMO #################################"
-	echo "BUILD COMMAND            : buildiso ${SCOPE:+-f} -p community/$EDITION -b $MANJAROBRANCH -k ${KERNEL_NAME} ${OFFICE:+-o}"
+	echo "BUILD COMMAND            : buildiso ${SCOPE:+-f} -p $EDITION -b $MANJAROBRANCH -k ${KERNEL_NAME} ${OFFICE:+-o}"
 	echo "PROFILE_PATH             : $PROFILE_PATH"
 	echo "EDITION                  : $EDITION"
 	echo "MANJAROBRANCH            : $MANJAROBRANCH"
@@ -545,7 +545,7 @@ build_iso() {
 	echo "PATH_MANJARO_ISO_PROFILES: $PATH_MANJARO_ISO_PROFILES"
 	echo "###################################################################"
 	echo "DEBUG                    : $DEBUG"
-	echo "ROOT_RUN_DIR             : $(</root/.config/manjaro-tools/iso-profiles.conf || true)"
+#	echo "ROOT_RUN_DIR             : $(</root/.config/manjaro-tools/iso-profiles.conf || true)"
 	echo "BUILDUSER_RUN_DIR        : $(</home/builduser/.config/manjaro-tools/iso-profiles.conf || true)"
 	echo "###################################################################"
 
@@ -556,6 +556,12 @@ build_iso() {
 		sudo -u builduser bash -c "buildiso ${SCOPE:+-f} -p $EDITION -b $MANJAROBRANCH -k linux${KERNEL_NAME} ${OFFICE:+-o}; exit \$? > /dev/null"
 	fi
 	BUILD_EXIT_CODE=$?
+
+	# Se buildiso falhou, sair com o código de erro
+	if [[ $BUILD_EXIT_CODE -ne 0 ]]; then
+		echo "ERROR: buildiso command failed with exit code $BUILD_EXIT_CODE"
+		exit $BUILD_EXIT_CODE
+	fi
 
 	# Verificar arquivos de kernel e tentar cópia manual, independentemente do resultado do buildiso
 	# Checking kernel files in rootfs:"
@@ -576,12 +582,6 @@ build_iso() {
 
 	echo "Contents of /var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot:"
 	ls -la /var/lib/manjaro-tools/buildiso/${EDITION}/iso/boot
-
-	# Se buildiso falhou, sair com o código de erro
-	if [[ $BUILD_EXIT_CODE -ne 0 ]]; then
-		echo "ERROR: buildiso command failed with exit code $BUILD_EXIT_CODE"
-		exit $BUILD_EXIT_CODE
-	fi
 }
 export -f build_iso
 
